name: my-bindfs-mounts
version: '0.1'
summary: bindfs mounts helper, with persistence layer
description: |
  Here resides a kind of framework that let us instantiate mounts in the way `bindfs`
  command does, plus a persistence section, so a list of mounts can be stored in a
  support file.

grade: stable
# Classic confinement was used to allow internal commands to run mounts on host system.
# Originally a couple of interfaces were tested, with no positive results.
confinement: classic

apps:
  my-bindfs-mounts:
    command: usr/bin/my-bindfs-mounts
    # plugs:
    #   - fuse-support
    #   - mount-observe

parts:
  my-bindfs-mounts:
    plugin: dump
    source: src/